### ISSUE TITLE
rkyv 0.8.14 fails to compile with Rust nightly 1.95.0 (2026-02-08)

### ISSUE THREAD

**Issue by WiseMrMusa** [NethermindEth/stellar-private-payments#99]
### Description
The rkyv crate version 0.8.14 fails to compile when using the Rust nightly toolchain version 1.95.0 (2026-02-08). The compilation error indicates that the dangling() method is no longer available on std::alloc::Layout.

### Error 

```
error[E0599]: no method named `dangling` found for reference `&std::alloc::Layout` in the current scope
 --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rkyv-0.8.14/src/polyfill.rs:8:16
  |
8 |         layout.dangling()
  |                ^^^^^^^^
  |
help: there is a method `dangling_ptr` with a similar name
  |
8 |         layout.dangling_ptr()
  |                        ++++
```

### Environment 
Rust Version: 1.95.0-nightly (6efa357bf 2026-02-08)
Target: x86_64-unknown-linux-gnu
Crate: rkyv 0.8.14

### Steps to Reproduce

1. Install Rust nightly toolchain (2026-02-08 or later)
2. Add Miri component: rustup +nightly component add miri
3. Attempt to compile a project that depends on rkyv 0.8.14

### Expected Behavior
The crate should compile successfully with the latest nightly Rust toolchain.

### Actual Behavior
Compilation fails due to the `dangling()` method being removed or renamed to `dangling_ptr()` in the standard library.
